### ISSUE TITLE
Touch only shows feedback for one 

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/galaxy-zoo-touch-table#4]
When multiple touches are happening the app only show touch feedback for one of the touches

**Comment by wgranger** [comment]
I mistakenly just opened a new issue on this (since closed). I noticed this the other day when demoing the app on the floor.

Currently, the touch table doesn't represent multiple touches at the same time. For example, if my finger is held on the table pressing a button, no other touch gestures will be registered. This shouldn't be happening and could lead to a bad UX.

**Comment by wgranger** [comment]
Most button commands should probably be attached to a `touchUp` event so a user can cancel their action by moving off a button. Some buttons on the app might currently use `touchDown`
